x-service-templates:
  api: &api
    image: wellingtonbp/rinha_de_backend_pure_ex:v1
    networks:
      - payment-processor
      - rinha-backend-ex
    deploy:
      resources:
        limits:
          cpus: '0.69'
          memory: '169MB'

  server: &server
    image: nginx:1.27.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-backend-ex
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '12MB'

services:
  api1:
    <<: *api
    hostname: api1
    environment:
      RELEASE_COOKIE: rinha
      RELEASE_NODE: api@api1
      RELEASE_DISTRIBUTION: sname
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
      SIBLING: api@api2

  api2:
    <<: *api
    hostname: api2
    environment:
      RELEASE_COOKIE: rinha
      RELEASE_NODE: api@api2
      RELEASE_DISTRIBUTION: sname
      DEFAULT_URL: http://payment-processor-default:8080
      FALLBACK_URL: http://payment-processor-fallback:8080
      SIBLING: api@api1

  lb:
    <<: *server
    depends_on:
      - api1
      - api2

networks:
  payment-processor:
    external: true
  rinha-backend-ex:
    driver: bridge
