x-service-templates:
  api: &api
    image: gabrieleiro/rinha-de-backend-2025-api:6.0
    networks:
      - rinha-de-backend-2025
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"
    volumes:
      - /tmp:/tmp
    depends_on:
      - tracker

services:
  api-1: 
    <<: *api
    hostname: api-1
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      TRACKER_URI: "/tmp/tracker.sock"
      LOAD_BALANCER_URI: "/tmp/lb.sock"
      ADDRESS: "/tmp/api_1.sock"

  api-2:
    <<: *api
    hostname: api-2
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      LOAD_BALANCER_URI: "/tmp/lb.sock"
      TRACKER_URI: "/tmp/tracker.sock"
      ADDRESS: "/tmp/api_2.sock"

  api-3:
      <<: *api
      hostname: api-3
      environment:
        DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
        FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
        LOAD_BALANCER_URI: "/tmp/lb.sock"
        TRACKER_URI: "/tmp/tracker.sock"
        ADDRESS: "/tmp/api_3.sock"

  api-4:
      <<: *api
      hostname: api-4
      environment:
        DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
        FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
        TRACKER_URI: "/tmp/tracker.sock"
        LOAD_BALANCER_URI: "/tmp/lb.sock"
        ADDRESS: "/tmp/api_4.sock"

  load-balancer:
    image: gabrieleiro/rinha-de-backend-2025-load-balancer:6.0
    networks:
      - rinha-de-backend-2025
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    volumes:
      - /tmp:/tmp
    ports:
      - "9999:9999"
    environment:
      UNIX_SOCKET_ADDRESS: "/tmp/lb.sock"
      TCP_ADDRESS: ":9999"
      SERVERS: "/tmp/api_1.sock,/tmp/api_2.sock,/tmp/api_3.sock,/tmp/api_4.sock"
    depends_on:
      - api-1
      - api-2
      - api-3
      - api-4

  tracker:
    hostname: tracker
    image: gabrieleiro/rinha-de-backend-2025-tracker:6.0
    networks:
      - rinha-de-backend-2025
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    volumes:
      - /tmp:/tmp
    environment:
      ADDRESS: "/tmp/tracker.sock"

networks:
  rinha-de-backend-2025:
    name: rinha-de-backend-2025
    driver: bridge
  payment-processor:
    external: true
