x-service-templates:
  api: &api
    image: gabrieleiro/rinha-de-backend-2025-api:3.0
    networks:
      - rinha-de-backend-2025
      - payment-processor
    volumes:
      - sockets_volume:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"
    depends_on:
      - tracker

services:
  api-1: 
    <<: *api
    hostname: api-1
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      TRACKER_URI: "/sockets/tracker.sock"
      LOAD_BALANCER_URI: "/sockets/load_balancer.sock"
      ADDRESS: "/sockets/api1.sock"

  api-2:
    <<: *api
    hostname: api-2
    environment:
      DEFAULT_PROCESSOR_URL: "http://payment-processor-default:8080"
      FALLBACK_PROCESSOR_URL: "http://payment-processor-fallback:8080"
      TRACKER_URI: "/sockets/tracker.sock"
      LOAD_BALANCER_URI: "/sockets/load_balancer.sock"
      ADDRESS: "/sockets/api2.sock"

  load-balancer:
    image: gabrieleiro/rinha-de-backend-2025-load-balancer:3.0
    networks:
      - rinha-de-backend-2025
    volumes:
      - sockets_volume:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    ports:
      - "9999:9999"
    environment:
      ADDRESS: ":9999"
      ADDRESS_UNIX: "/sockets/load_balancer.sock"
      SERVERS: "/sockets/api1.sock,/sockets/api2.sock"
    depends_on:
      - api-1
      - api-2

  tracker:
    hostname: tracker
    image: gabrieleiro/rinha-de-backend-2025-tracker:3.0
    networks:
      - rinha-de-backend-2025
    volumes:
      - sockets_volume:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    environment:
      ADDRESS: "/sockets/tracker.sock"

networks:
  rinha-de-backend-2025:
    name: rinha-de-backend-2025
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets_volume:
