services:

  backend01: &backend
    image: thiagorigonatti/rinha-2025-scratch:0.0.13
#    build:
#      context: .
#      dockerfile: scratch.Dockerfile
    container_name: backend01
    environment:
      - HTTP_CLIENT_THREADS=3
      - SOCKET_SERVER_THREADS=3
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "50MB"
    ipc: container:shared-memory
    depends_on:
      - shared-memory


  backend02:
    <<: *backend
    container_name: backend02
    environment:
      - HTTP_CLIENT_THREADS=3
      - SOCKET_SERVER_THREADS=3
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock


  shared-memory:
    image: alpine:latest
    command: tail -f /dev/null
    ipc: shareable
    shm_size: 512mb
    container_name: shared-memory
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "8MB"


  haproxy:
    image: haproxy:3.3-dev6-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "100MB"
    depends_on:
      - backend01
      - backend02
    ipc: container:shared-memory


networks:
  net:
    driver: bridge
  payment-processor:
    external: true
