services:

  backend01: &backend
    image: thiagorigonatti/rinha-2025-scratch:0.0.15
    #    build: .
    container_name: backend01
    environment:
      - HTTP_CLIENT_THREADS=1
      - HTTP_SERVER_THREADS=1
      - INDEX=0
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "10MB"
    ipc: container:shared-memory
    depends_on:
      - shared-memory
    cpuset: "0,2"


  backend02:
    <<: *backend
    container_name: backend02
    environment:
      - HTTP_CLIENT_THREADS=1
      - HTTP_SERVER_THREADS=1
      - INDEX=1
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock
    cpuset: "1,3"

  shared-memory:
    image: alpine:latest
    command: tail -f /dev/null
    ipc: shareable
    shm_size: 512kb
    container_name: shared-memory
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "8MB"


  haproxy:
    image: haproxy:3.3-dev6-alpine3.22
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "50MB"
    depends_on:
      - backend01
      - backend02
      - shared-memory
    ipc: container:shared-memory


networks:
  net:
    driver: bridge
  payment-processor:
    external: true
