services:

  backend01: &backend
    image: thiagorigonatti/rinha-2025-scratch:0.0.4
    container_name: backend01
    environment:
      - HTTP_CLIENT_THREADS=3
      - SOCKET_SERVER_THREADS=3
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "8MB"
    ipc: container:shared-memory
    cpuset: "0,2,4"
    depends_on:
      - shared-memory

  backend02:
    <<: *backend
    container_name: backend02
    environment:
      - HTTP_CLIENT_THREADS=3
      - SOCKET_SERVER_THREADS=3
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock
    ipc: container:shared-memory
    cpuset: "1,3,5"

  shared-memory:
    image: alpine:3.18
    command: tail -f /dev/null
    ipc: shareable
    shm_size: 512kb
    container_name: shared-memory
    deploy:
      resources:
        limits:
          cpus: "0.02"
          memory: "8MB"

  haproxy:
    image: haproxy:3.3-dev5-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.38"
          memory: "200MB"
    depends_on:
      - backend01
      - backend02
    ipc: container:shared-memory

networks:
  net:
    driver: bridge
  payment-processor:
    external: true
