services:

  backend01: &backend
    image: thiagorigonatti/rinha-2025-scratch:0.0.7
    build:
      context: .
      dockerfile: scratch.Dockerfile
    container_name: backend01
    environment:
      - HTTP_CLIENT_THREADS=6
      - SOCKET_SERVER_THREADS=6
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "60MB"
    ipc: container:shared-memory
    depends_on:
      - shared-memory
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend02:
    <<: *backend
    container_name: backend02
    environment:
      - HTTP_CLIENT_THREADS=6
      - SOCKET_SERVER_THREADS=6
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock
    ipc: container:shared-memory

  backend03:
    <<: *backend
    container_name: backend03
    environment:
      - HTTP_CLIENT_THREADS=1
      - SOCKET_SERVER_THREADS=1
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server3.sock
    ipc: container:shared-memory

  shared-memory:
    image: alpine:latest
    command: tail -f /dev/null
    ipc: shareable
    shm_size: 512kb
    container_name: shared-memory
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "20MB"

  haproxy:
    image: haproxy:3.3-dev6-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "150MB"
    depends_on:
      - backend01
      - backend02
      - backend03
    ipc: container:shared-memory
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  net:
    driver: bridge
  payment-processor:
    external: true
