services:

  backend01: &backend
    image: thiagorigonatti/rinha-2025-scratch:0.0.5
    container_name: backend01
    environment:
      - SOCKET_SERVER_CPU=1
      - HTTP_CLIENT_CPU=2
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server1.sock
    networks:
      - net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "8MB"
    ipc: container:shared-memory
    cpuset: "1,2"
    depends_on:
      - shared-memory
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend02:
    <<: *backend
    container_name: backend02
    environment:
      - SOCKET_SERVER_CPU=3
      - HTTP_CLIENT_CPU=4
      - SHM_PATH=/shm_array
      - SOCKET_PATH=/dev/shm/server2.sock
    ipc: container:shared-memory
    cpuset: "3,4"

  shared-memory:
    image: alpine:latest
    command: tail -f /dev/null
    ipc: shareable
    shm_size: 512kb
    container_name: shared-memory
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "8MB"
    cpuset: "5"

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.49"
          memory: "128MB"
    depends_on:
      - backend01
      - backend02
    ipc: container:shared-memory
    cpuset: "5"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
networks:
  net:
    driver: bridge
  payment-processor:
    external: true
