services:
  api01: &app
    image: thiagorigonatti/rinha-2025:0.0.6
    environment:
      - PTHREADS=3
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "20MB"
    volumes:
      - /dev/shm:/dev/shm

  api02:
    <<: *app

  haproxy:
    image: haproxy:3.3-dev5-alpine3.22
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"
    networks:
      - api
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
