services:
  api: &api
    image: ghcr.io/diofeher/rinha-de-backend-2025-diofeher:main-969c435
    depends_on:
      - redis
    environment:
      - DEBUG=false
      - PORT=8080
      - REDIS_URL=redis:6379
      - REDIS_DB=rinha
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - QUEUE_BATCH_SIZE=1
      - NUM_WORKERS=50
    deploy:
      resources:
        limits:
          cpus: "1.45"
          memory: "250MB"
    ports:  # turn off if put nginx in front of the app
      - "9999:8080"
    networks:
      - backend
      - payment-processor
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=rinha
    command: >
      redis-server --maxclients 4096 --save "" --appendonly no
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "100MB"

# cpus: nginx 0.15 apps 0.30 redis 1.15 = 1.5 total 
# # memory: nginx 15MB apps 30MB redis 305MB = 350MB total 

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
