services:
  lb:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 90M
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socket-volume:/socket
    ports:
      - "9999:9999"
    command: >
      sh -c '
        echo "Await app1 and app2...";
        until curl -fs --unix-socket /socket/app1.sock http://localhost/healthcheck; do
          echo "Await app-1...";
          sleep 0.2;
        done;
        until curl -fs --unix-socket /socket/app2.sock http://localhost/healthcheck; do
          echo "Await app-2...";
          sleep 0.2;
        done;
        echo "All ready! init NGINX...";
        nginx -g "daemon off;";
      '
    depends_on:
      - app-1
      - app-2

  app-1: &app-base
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 80M
    image: daviddeltasierra/rinha-2025-go
    volumes:
      - socket-volume:/socket
    environment:
      - SOCKET_PATH=/socket/app1.sock
    depends_on:
      - postgres

  app-2:
    <<: *app-base
    environment:
      - SOCKET_PATH=/socket/app2.sock

  postgres:
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
    image: postgres:alpine
    user: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha

volumes:
  socket-volume:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true