services:
  api:
    image: felipeschirmann/rinha-backend-2025:7.0.0
    container_name: felipeschirmann-rinha-v7
    environment:
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    sysctls:
      net.core.somaxconn: 4096
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus:  "1.5"
          memory: "350MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true