services:
  app1:
    image: pedrohsbarbosa99/rinha-golang-2025:0.2.3
    command: ["./main"]
    environment:
      - SUMMARY_URL=http://app2:8080/internal/payments-summary
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 70M
    restart: unless-stopped

  app2:
    image: pedrohsbarbosa99/rinha-golang-2025:0.2.3
    command: ["./main"]
    environment:
      - SUMMARY_URL=http://app1:8080/internal/payments-summary
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - memsock:/tmp
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 70M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-1
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    restart: unless-stopped

volumes:
  memsock:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

