services:
  api:
    image: vhogemann/rinha-de-backend-2025-fsharp:latest
    ports:
        - "9999:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true