x-service-templates:
  backend-service: &backend-service
    image: ghcr.io/4emcos/rinha-backend-2025-golang:1.0.4
    environment: &backend-env
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      REDIS_URL: redis:6379
    networks:
      - payment-processor
      - backend
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "70MB"

services:
  backend-01:
    <<: *backend-service
    container_name: backend-01
    hostname: backend-01

  backend-02:
    <<: *backend-service
    container_name: backend-02
    hostname: backend-02

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: |
      redis-server 
      --save ""
      --appendonly no
      --maxmemory 40mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 300
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-01:
        condition: service_healthy
      backend-02:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true