services:
  backend-01: &backend
    image: ghcr.io/4emcos/rinha-backend-2025-golang:1.0.0
    container_name: backend-01
    hostname: backend-01
    environment:
      APP_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      REDIS_URL: redis:6379
    networks:
      - payment-processor
      - backend
    depends_on:
      - redis
    expose:
      - 5000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "70MB"

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true