x-api-template: &api-template
    image: adrianomoreira86/rinha-de-backend-2025-java-quarkus:v2
    networks:
      - app
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "96MB"
    environment:
      quarkus.datasource.db-kind: postgresql
      quarkus.datasource.username: admin
      quarkus.datasource.password: 123
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/rinha
      quarkus.datasource.jdbc.max-size: 24
      quarkus.rest-client.processor-default.url: http://payment-processor-default:8080/
      quarkus.rest-client.processor-default.read-timeout: 12000
      quarkus.rest-client.processor-default.connect-timeout: 1000
      quarkus.rest-client.processor-fallback.url: http://payment-processor-default:8080/
      quarkus.rest-client.processor-fallback.read-timeout: 12000
      quarkus.rest-client.processor-fallback.connect-timeout: 1000
      quarkus.log.level: INFO

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - quarkus-backend-1
      - quarkus-backend-2
    ports:
      - "9999:9999"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  quarkus-backend-1:
    <<: *api-template
  quarkus-backend-2:
    <<: *api-template

  postgres:
    image: postgres:17
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "rinha", "-U", "admin" ]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - app
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true