services:
  api-1:
    hostname: api-1
    image: gabxdevv/rinha-backend-2025-java-super-bolado-native-nginx:1.0.0
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 14
      WORKERS_THREAD_POOL_SIZE: 12
      USER_SERVER: true
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      BACK_END_URL: http://backend-2:8080
      UDP_CHANNEL_PORT: 9001
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: api-2
      EXTERNAL_UDP_PORT: 9004
      SERVER_PORT: 8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.675'
          memory: '150MB'

  api-2:
    hostname: api-2
    image: gabxdevv/rinha-backend-2025-java-super-bolado-native-nginx:1.0.0
    restart: always
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 14
      WORKERS_THREAD_POOL_SIZE: 12
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      USER_SERVER: false
      BACK_END_URL: http://backend-1:8080
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: api-1
      EXTERNAL_UDP_PORT: 9003
      SERVER_PORT: 8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.675'
          memory: '150MB'

  load-balancer:
    image: haproxy:3.2.3-alpine
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true