services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "55MB"

  api1:
    image: danielsuhett1999/rinha-backend
    hostname: api1
    environment:
      - APP_PORT=8080
      - APP_MODE=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "70MB"

  api2:
    image: danielsuhett1999/rinha-backend
    hostname: api2
    environment:
      - APP_PORT=8081
      - APP_MODE=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "70MB"
  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxmemory 150mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 0 --tcp-backlog 511 --databases 1 --maxclients 10000 --hz 100 --rdbcompression no --rdbchecksum no
    networks:
      - backend
      - payment-processor
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "150MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true