x-enviromments: &x-enviromments
  - SQLITE_PATH: "/dev/shm/database.sqlite3?sync=off&journal_mode=WAL&busy_timeout=1000&cache_size=100000"
  - AMQP_URL: "amqp://guest:guest@lavinmq:5672/"
  - BATCH_INTERVAL: "50"
  - PREFETCH_COUNT: "0"
  - SHARD_COUNT: "1"
  - SKIP_DELAY: "true"
  - PROCESSOR_URL: "http://payment-processor-default:8080"
  - FALLBACK_URL: "http://payment-processor-fallback:8080"
  - DISABLE_LOG: "true"

version: '3.4'
services:
  app1: &app
    image: docker.io/lukas8219/rinha-de-backend-2025-app:main-a0daa45f7-1753099550
    hostname: app1
    restart: unless-stopped
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app1.sock"
    networks:
      - backend
      - payment-processor
    expose:
      - "3000"
    ipc: host
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '50MB'
  app2:
    <<: *app
    environment:
      <<: *x-enviromments
      SOCKET_PATH: "/dev/shm/app2.sock"
    hostname: app2
    depends_on:
      lavinmq:
        condition: service_healthy
      consumer:
        condition: service_started

  consumer:
    <<: *app
    hostname: "1"
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '180MB'
    image: docker.io/lukas8219/rinha-de-backend-2025-worker:main-a0daa45f7-1753099550
    cpu_shares: 2048
    cpuset: "0"
    depends_on:
      lavinmq:
        condition: service_healthy

  cleanup:
    image: alpine:latest
    command: ["/bin/sh", "-c", "rm -rf /dev/shm/*"]
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: '10MB'
    restart: "no"
    networks:
      - backend

  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    healthcheck:
      test: ["CMD", "lavinmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    depends_on:
      - cleanup
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '35MB'

  nginx: # Load Balancer
    ipc: host
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - lavinmq
      - consumer
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '25MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
