version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-1
      - app-2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    restart: always
    networks:
      - rinha-net

  app-1:
    image: samuka7abrr/my-rinha-backend:latest
    container_name: app-1
    environment:
      - DB_HOST=rinha-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      - REDIS_ADDR=rinha-redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    expose:
      - "8080"
    depends_on:
      - rinha-postgres
      - rinha-redis
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 64M
    restart: always
    networks:
      - rinha-net
      - payment-processor

  app-2:
    image: samuka7abrr/my-rinha-backend:latest
    container_name: app-2
    environment:
      - DB_HOST=rinha-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha
      - REDIS_ADDR=rinha-redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    expose:
      - "8080"
    depends_on:
      - rinha-postgres
      - rinha-redis
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 64M
    restart: always
    networks:
      - rinha-net
      - payment-processor

  postgres:
    image: postgres:16-alpine
    container_name: rinha-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.20" 
          memory: "50MB"  
    restart: always
    networks:
      - rinha-net

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    deploy:
      resources:
        limits:
          cpus: "0.10" 
          memory: "20MB"  
    restart: always
    networks:
      - rinha-net

volumes:
  pgdata:

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true