services:
  load-balance:
    image: lpj145/rinha-lb:1.03
    environment:
      - MAX_CONNECTIONS=10
    networks:
      - backend
      - payment-processor
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "40MB"
volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
