x-api_template: &api_template
  image: rodrigoknolseisen/rinha-2025-payment-processor-c:latest
  restart: unless-stopped
  environment:
    PORT: 3000
    BACKGROUND_WORKERS_COUNT: 3
    DB_PATH: "db/"
    VERBOSE: "false"
  networks:
    - payment-processor-server-network
    - payment-processor
  volumes:
    - shared_data:/db
  deploy:
    resources:
      limits:
        cpus: "0.40"
        memory: "95MB"

services:
  api01:
    <<: *api_template
    hostname: api01
  api02:
    <<: *api_template
    hostname: api02
  api03:
    <<: *api_template
    hostname: api03
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api01
      - api02
      - api03
    networks:
      - payment-processor-server-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "65MB"

networks:
  payment-processor-server-network:
    driver: bridge
  payment-processor:
    driver: bridge
    external: true

volumes:
  shared_data:
    driver: local
